### ISSUE TITLE
**not an issue** VPN Tab and Firmware

### ISSUE THREAD

**Issue by kevdagoat** [wuseman/TG799VAC-XTREME-17.2-MINT#2]
I have found this after looking for Netgear Source instructions :)

I see on your specific modem you have a vpn tab?
Also do you know that you don't need to destroy your firmware URL's and can I grab your 16.3 one to add to the Technicolor Firmware Repository (https://whirlpool.net.au/wiki/hw_model_1622)?

For your info you can find the more official TG799 hacking forum here:
https://forums.whirlpool.net.au/forum-replies.cfm?t=2650998&p=-1&#bottom

**Comment by kevdagoat** [comment]
Oh and I see you have my telephony modal under the modified gui's home page :)

**Comment by kevdagoat** [comment]
Thanks for that!

Will pull out my spare and have a go tonight

**Comment by kevdagoat** [comment]
Doesn't work :(
Could you run:
ls /etc/config/ 

And I will compare to mine.
Can I also grab your /lib/functions/firewall-l2tp-ipsec-server.sh file as mine doesn't exist?

**Comment by wuseman** [comment]
Wich version do you use atm?

I had no time to try add the vpn tab on v16.3 this night, I got stuck all night trying to get new features on current setup 17.2.

Of course, here you go: 

![Screenshot](https://sendit.nu/f/VxHsaZoRpJ%28Zw.png)

I already uploaded /lib/functions/firewall-l2tp-ipsec-server.sh for you, you can grab it here:
https://raw.githubusercontent.com/wuseman/TG799VAC-XTREME-17.2-MINT/master/lib/functions/firewall-l2tp-ipsec-server.sh

Just let me if there's anything else I can help you with.

**Comment by wuseman** [comment]
**vpn config file:**
config l2tpipsecserver 'l2tpipsecserver'
        option enable '0'
        option local_ip '192.168.1.245'
        option remote_ip_start '192.168.1.246'
        option remote_ip_end '192.168.1.253'
        option proxyarp '1'

config l2tp_user
        option name 'vpn_user'
        option password 'yuhLacc7nSwR'

**fcctlsettings:**
config state 'state'
        option enabled '1'

config option 'option'
                option l2tp '1'
                option gre '1'
                option ipv6 '1'
                option mcast '1'
                option mcast_learn '1'

**/etc/services:**
openvpn         1194/tcp
openvpn         1194/udp

**Comment by kevdagoat** [comment]
Thanks for that.

I have the TG799vac (non XTREAM) and will have to install openvpn.

Here is my install script so far:

####FIREWALL####
uci add_list fcctlsettings.option.l2tp='1'
uci set firewall.@forwarding[13].dest='vpn'
uci add_list firewall.@forwarding[14].src='vpn'
uci add_list firewall.@forwarding[15].src='vpn'
uci add_list firewall.@forwarding[5].dest='vpn'
uci add_list firewall.@forwarding[6].src='vpn'
uci add_list firewall.@forwarding[7].src='vpn'
uci add_list firewall.l2tpipsecserver.path='/lib/functions/firewall-l2tp-ipsec-server.sh'
uci add_list firewall.l2tpipsecserver.reload='1'
uci add_list firewall.l2tpipsecserver.type='script'
uci add_list firewall.l2tpipsecserver=include
uci add_list firewall.vpn.device='ppp+'
uci add_list firewall.vpn.forward='ACCEPT'
uci add_list firewall.vpn.input='ACCEPT'
uci add_list firewall.vpn.masq='0'
uci add_list firewall.vpn.mtu_fix='1'
uci add_list firewall.vpn.name='vpn'
uci add_list firewall.vpn.output='ACCEPT'
uci add_list firewall.vpn.subnet='192.168.1.246-192.168.1.253'
uci add_list firewall.vpn.wan='0'
uci add_list firewall.vpn=zone

####IPSec####
uci add_list ipsec.l2tp.authentication_method='psk'
uci add_list ipsec.l2tp.crypto_proposal='g_3des_sha1_modp1024 g_aes128_sha1'
uci add_list ipsec.l2tp.enabled='0'
uci add_list ipsec.l2tp.gateway='any'
uci add_list ipsec.l2tp.pre_shared_key='e9aqG4ksmH3nKbaua5ps'
uci add_list ipsec.l2tp.transport='server'
uci add_list ipsec.l2tp=remote
uci add_list ipsec.server.local_subnet='0.0.0.0/0[udp/l2tp]'

####L2TP####
uci add_list vpn.@l2tp_user[0]._key='C06DB323FFF3EF27D06AF44E172604'
uci add_list vpn.@l2tp_user[0].name='vpn_user'
uci add_list vpn.@l2tp_user[0].password='zNsaxqtGyNfw'
uci add_list vpn.@l2tp_user[0]=l2tp_user
uci add_list vpn.l2tpipsecserver.enable='0'
uci add_list vpn.l2tpipsecserver.local_ip='192.168.1.245'
uci add_list vpn.l2tpipsecserver.proxyarp='1'
uci add_list vpn.l2tpipsecserver.remote_ip_end='192.168.1.253'
uci add_list vpn.l2tpipsecserver.remote_ip_start='192.168.1.246'
uci add_list vpn.l2tpipsecserver=l2tpipsecserver

####WEB####
uci set web.l2tpipsecservermodal=rule
uci add_list web.ruleset_main.rules=l2tpipsecservermodal
uci set web.l2tpipsecservermodal.target='/modals/l2tp-ipsec-server-modal.lp'
uci set web.l2tpipsecservermodal=rule
uci add_list web.l2tpipsecservermodal.roles='admin'

Output(expected):

root@mygateway:~# uci add_list firewall.@forwarding[14].src='vpn'
uci: Invalid argument
root@mygateway:~# uci add_list firewall.@forwarding[15].src='vpn'
uci: Invalid argument
root@mygateway:~# uci add_list firewall.@forwarding[5].dest='vpn'
uci: Invalid argument
root@mygateway:~# uci add_list firewall.@forwarding[6].src='vpn'
uci: Invalid argument
root@mygateway:~# uci add_list firewall.@forwarding[7].src='vpn'
uci: Invalid argument
root@mygateway:~# uci add_list firewall.l2tpipsecserver.path='/lib/functions/fir
ewall-l2tp-ipsec-server.sh'
uci: Invalid argument
root@mygateway:~# uci add_list firewall.l2tpipsecserver.reload='1'
uci: Invalid argument
root@mygateway:~# uci add_list firewall.l2tpipsecserver.type='script'
uci: Invalid argument
root@mygateway:~# uci add_list firewall.l2tpipsecserver=include
uci: Invalid argument
root@mygateway:~# uci add_list firewall.vpn.device='ppp+'
uci: Invalid argument
root@mygateway:~# uci add_list firewall.vpn.forward='ACCEPT'
uci: Invalid argument
root@mygateway:~# uci add_list firewall.vpn.input='ACCEPT'
uci: Invalid argument
root@mygateway:~# uci add_list firewall.vpn.masq='0'
uci: Invalid argument
root@mygateway:~# uci add_list firewall.vpn.mtu_fix='1'
uci: Invalid argument
root@mygateway:~# uci add_list firewall.vpn.name='vpn'
uci: Invalid argument
root@mygateway:~# uci add_list firewall.vpn.output='ACCEPT'
uci: Invalid argument
root@mygateway:~# uci add_list firewall.vpn.subnet='192.168.1.246-192.168.1.253'
uci: Invalid argument
root@mygateway:~# uci add_list firewall.vpn.wan='0'
uci: Invalid argument
root@mygateway:~# uci add_list firewall.vpn=zone
uci: Invalid argument
root@mygateway:~#
root@mygateway:~# ####IPSec####
root@mygateway:~# uci add_list ipsec.l2tp.authentication_method='psk'
uci: Entry not found
root@mygateway:~# uci add_list ipsec.l2tp.crypto_proposal='g_3des_sha1_modp1024
g_aes128_sha1'
uci: Entry not found
root@mygateway:~# uci add_list ipsec.l2tp.enabled='0'
uci: Entry not found
root@mygateway:~# uci add_list ipsec.l2tp.gateway='any'
uci: Entry not found
root@mygateway:~# uci add_list ipsec.l2tp.pre_shared_key='e9aqG4ksmH3nKbaua5ps'
uci: Entry not found
root@mygateway:~# uci add_list ipsec.l2tp.transport='server'
uci: Entry not found
root@mygateway:~# uci add_list ipsec.l2tp=remote
uci: Entry not found
root@mygateway:~# uci add_list ipsec.server.local_subnet='0.0.0.0/0[udp/l2tp]'
uci: Entry not found
root@mygateway:~#
root@mygateway:~# ####L2TP####
root@mygateway:~# uci add_list vpn.@l2tp_user[0]._key='C06DB323FFF3EF27D06AF44E1
72604'
uci: Entry not found
root@mygateway:~# uci add_list vpn.@l2tp_user[0].name='vpn_user'
uci: Entry not found
root@mygateway:~# uci add_list vpn.@l2tp_user[0].password='zNsaxqtGyNfw'
uci: Entry not found
root@mygateway:~# uci add_list vpn.@l2tp_user[0]=l2tp_user
uci: Entry not found
root@mygateway:~# uci add_list vpn.l2tpipsecserver.enable='0'
uci: Entry not found
root@mygateway:~# uci add_list vpn.l2tpipsecserver.local_ip='192.168.1.245'
uci: Entry not found
root@mygateway:~# uci add_list vpn.l2tpipsecserver.proxyarp='1'
uci: Entry not found
root@mygateway:~# uci add_list vpn.l2tpipsecserver.remote_ip_end='192.168.1.253'
uci: Entry not found
root@mygateway:~# uci add_list vpn.l2tpipsecserver.remote_ip_start='192.168.1.24
6'
uci: Entry not found
root@mygateway:~# uci add_list vpn.l2tpipsecserver=l2tpipsecserver
uci: Entry not found
root@mygateway:~#
root@mygateway:~# ####WEB####
root@mygateway:~# uci add_list web.ruleset_main.rules=l2tpipsecservermodal
root@mygateway:~# uci set web.l2tpipsecservermodal.target='/modals/l2tp-ipsec-se
rver-modal.lp'
uci: Invalid argument
root@mygateway:~# uci set web.l2tpipsecservermodal=rule
root@mygateway:~# uci add_list web.l2tpipsecservermodal.roles='admin'
root@mygateway:~# uci set web.l2tpipsecservermodal=rule
uci add_list web.ruleset_main.rules=l2tpipsecservermodal
uci set web.l2tpipsecservermodal.target='/modals/l2tp-ipsec-server-modal.lp'
uci set web.l2tpipsecservermodal=rule
uci add_list web.l2tpipsecservermodal.roles='admin'root@mygateway:~# uci add_lis                                                                                                                                                             t web.ruleset_main.rules=l2tpipsecservermodal
root@mygateway:~# uci set web.l2tpipsecservermodal.target='/modals/l2tp-ipsec-se
rver-modal.lp'
root@mygateway:~# uci set web.l2tpipsecservermodal=rule
root@mygateway:~# uci add_list web.l2tpipsecservermodal.roles='admin'
root@mygateway:~#

**Comment by kevdagoat** [comment]
Ahh of course. These things have special needs...

/etc/opkg$ opkg install openvpn-openssl
Installing openvpn-openssl (2.3.6-5) to root...
Downloading http://archive.openwrt.org/chaos_calmer/15.05.1/brcm63xx/generic/packages/base/openvpn-openssl_2.3.6-5_brcm63xx.ipk.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for openvpn-openssl:
 * 	kernel (= 3.18.23-1-df7efb22d5e24c34e407197985d2f684) * 
 * opkg_install_cmd: Cannot install package openvpn-openssl.

**Comment by kevdagoat** [comment]
To stop hassling you, can I grab Telia's firmware key?
http://whrl.pl/RfcWZv
http://whrl.pl/Rfb4CF

**Comment by kevdagoat** [comment]
If you want to do it and send it to me, here is the script.
https://app.box.com/s/2jtlbobwnff1lmcv94br8jhl5j4mpsxo

To use:
1) Replace Key
2) Upload to modem along with firmware
3) chmod it
4) execute including firmware directory
5) Done, you now have a .bin file.

**Comment by wuseman** [comment]
Sure, i just made a VIDEO for you. I can confirm the VPN tab works on firmware 16.2 Jade aswell.

Watch the video here: https://sendit.nu/f/add_vpn-tab.gif , it was to big to view here.

Nice, let me try to get the key.

**Comment by kevdagoat** [comment]
Thanks for that!
Good luck with the keys.

Sent from Mail for Windows 10

**Comment by wuseman** [comment]
> If you want to do it and send it to me, here is the script.
> https://app.box.com/s/2jtlbobwnff1lmcv94br8jhl5j4mpsxo
> 
> To use:
> 
> 1. Replace Key
> 2. Upload to modem along with firmware
> 3. chmod it
> 4. execute including firmware directory
> 5. Done, you now have a .bin file.

Sorry i forgot this, i lost the zip. Please upload it again and i will share the key. 

Regards

**Comment by kevdagoat** [comment]
Looks like the zip link is broken :(

You can still get the key by running the commands in the posts I linked above

**Comment by wuseman** [comment]
Okey :/

Well, i can't get the eckey it seems, trying to run:
     
     insmod r2secr.mips.ko && dmesg
     Failed to find r2secr.mips. Maybe it is a built in module ?

If i trying to grep r2secr all i get is a a match in kernel command linem: 

      dmesg | grep r2
      [    0.000000] Kernel command line: console= .r2secr=0x1ffdf000 <

**Comment by kevdagoat** [comment]
Try insmod /path/to/r2secr.mips.ko && dmesg

Sent from Mail for Windows 10

**Comment by wuseman** [comment]
wow, it worked fine thanks..

So wich file you need i got many RIP files :)

**Comment by wuseman** [comment]
RIP_ID_GENERIC_ACCESS_KEY_LIST_0x0124-0b22c8d9 some of these files are the same as in /proc/rip folder

**Comment by kevdagoat** [comment]
Can I grab all of them?
The easiest way is:

hexdump /path/to/key


Sent from Mail for Windows 10

**Comment by wuseman** [comment]
Sure, where to upload?

**Comment by kevdagoat** [comment]
Google drive, pastebin, pastee, etc.

Sent from Mail for Windows 10

**Comment by wuseman** [comment]
Ok, i will fix asap.

**Comment by wuseman** [comment]
What is interesting is that we have /proc/rip and /prof/efu from a factory standard that's why i asked what is the benefit, i guess this is not default from technicolor then, well I will upload soon.

**Comment by kevdagoat** [comment]
Thanks for that!

Will look at decrypting some software tonight

**Comment by wuseman** [comment]
Cool, you it will be possible to get a openvpn tab?

**Comment by wuseman** [comment]
Okay, i got my new router finally. Do you guys got any idea how i can create a firmware 'rbi' file from current setup? I wanna clone the new router so i can fix my old one of same version with tftp and i need a bin or rbi file then it seems.

**Comment by kevdagoat** [comment]
You cant because the file needs signing.
We do not know the key 😊

Sent from Mail for Windows 10

**Comment by wuseman** [comment]
Okey, i see.

**Comment by wuseman** [comment]
Does the key contains 15 or 9 characters?

**Comment by kevdagoat** [comment]
Don’t know. Otherwise we would’ve done it already :)

**Comment by wuseman** [comment]
Okok, still working on it :-)

**Comment by wuseman** [comment]
Hey again, i have setup openvpn on my technicolor router again.

Uploaded a video and commands for setup openvpn below. Actually i am working on a script for install openvpn on a very simple way but it might take some time so I will show you exactly how i did.. (THIS IS BY COMMANDLINE ONLY)

**NOTICE** this is only for setup openvpn as a client, not as a server on your side so you will need vpn configurations - you also can set remote.ip, ports etc manually but i prefer to just scp over the configs and then set the settings below. 

##### Install openvpn-util 
opkg update
opkg install openvpn-openssl openvpn-util

##### Configure your vpn:
uci set openvpn.wuseman.uk_client=openvpn
uci set openvpn.wuseman.uk_client.enabled='1'
uci set openvpn.wuseman.uk_client.client='1'
uci set openvpn.wuseman.uk_client.dev='tun'
uci set openvpn.wuseman.uk_client.proto='udp'
uci set openvpn.wuseman.uk_client.resolv_retry='infinite'
uci set openvpn.wuseman.uk_client.persist_key='1'
uci set openvpn.wuseman.uk_client.persist_tun='1'
uci set openvpn.wuseman.uk_client.ca='/etc/openvpn/wuseman.uk/keys/ca.crt'
uci set openvpn.wuseman.uk_client.cert='/etc/openvpn/wuseman.uk/keys/wuseman.crt'
uci set openvpn.wuseman.uk_client.key='/etc/openvpn/wuseman.uk/keys/wuseman.key'
uci set openvpn.wuseman.uk_client.csr='/etc/openvpn/wuseman.uk/keys/wuseman.csr'
uci set openvpn.wuseman.uk_client.tls_auth='/etc/openvpn/wuseman.uk/keys/tls-auth.key 1'
uci set openvpn.wuseman.uk_client.config='/etc/openvpn/wuseman.uk/openvpn.conf'
uci set openvpn.wuseman.uk_client.comp_lzo='yes'
uci set openvpn.wuseman.uk_client.verb='3'

##### Network Interface For TUN (required) 
uci set network.wuseman.uk_client=interface      
uci set network.wuseman.uk_client.proto='dhcp'           # Options: 'dhcp' 'none'
uci set network.wuseman.uk_client.ifname='tun0'         # Wont be listed in 'ifconfig' so dont be confused

##### Firewall 
echo "# Generated by w-openvpn-install.sh" > w-openvpn.log
uci add firewall zone >>  w-openvpn.log
uci set firewall.@zone[-1].name='vpn'
uci set firewall.@zone[-1].input='REJECT'
uci set firewall.@zone[-1].output='ACCEPT'
uci set firewall.@zone[-1].forward='REJECT'
uci set firewall.@zone[-1].masq='1'
uci set firewall.@zone[-1].mtu_fix='1'
uci add_list firewall.@zone[-1].network='wuseman.uk_client'

##### Now we need forward our lan2vpn
uci add firewall forwarding
uci set firewall.@forwarding[-1].src='lan'
uci set firewall.@forwarding[-1].dest='vpn'

##### REQUIRED - Set This OR You Will Be Without Internet
uci add_list dhcp.lan.dhcp_option='6,8.8.8.8,8.8.4.4'
uci set network.wan.peerdns='0'                                   # Disable DNS provided by DHCP
uci del network.wan.dns                                                # Deletes the previous list of DNS if exist.
uci add_list network.wan.dns='8.8.8.8'                          # Google Public DNS, it works perfect
uci add_list network.wan.dns='8.8.4.4'                          # ... -:- ^

#####  Commit Changes
uci commit

##### Get connected.
/etc/init.d/network start                                                                    # Restart network.
/etc/init.d/firewall reload                                                                   # Reload firewall rules
/etc/init.d/openvpn start                                                                   # Starting openvpn

##### This is output from my syslog:
Mon Nov  5 17:38:33 2018 daemon.notice openvpn(wuseman.uk_client)[3313]: OpenVPN 2.3.6 [SSL (OpenSSL)] [LZO] [EPOLL] [MH] [IPv6] built on Jul 25 2015
Mon Nov  5 17:38:33 2018 daemon.notice openvpn(wuseman.uk_client)[3313]: library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Mon Nov  5 17:38:33 2018 daemon.warn openvpn(wuseman.uk_client)[3313]: WARNING: file 'keys/wuseman.key' is group or others accessible
Mon Nov  5 17:38:33 2018 daemon.warn openvpn(wuseman.uk_client)[3313]: WARNING: file 'keys/tls-auth.key' is group or others accessible
Mon Nov  5 17:38:33 2018 daemon.notice openvpn(wuseman.uk_client)[3313]: Control Channel Authentication: using 'keys/tls-auth.key' as a OpenVPN static key file
Mon Nov  5 17:38:33 2018 daemon.notice openvpn(wuseman.uk_client)[3313]: Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Mon Nov  5 17:38:33 2018 daemon.notice openvpn(wuseman.uk_client)[3313]: Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Mon Nov  5 17:38:34 2018 daemon.notice openvpn(wuseman.uk_client)[3313]: Socket Buffers: R=[163840->131072] S=[163840->131072]
Mon Nov  5 17:38:34 2018 daemon.notice openvpn(wuseman.uk_client)[3313]: UDPv4 link local: [undef]
Mon Nov  5 17:38:34 2018 daemon.notice openvpn(wuseman.uk_client)[3313]: UDPv4 link remote: [AF_INET]xxx.xxx.xxx.xx:1194
Mon Nov  5 17:38:34 2018 daemon.notice openvpn(wuseman.uk_client)[3313]: TLS: Initial packet from [AF_INET]xxx.xxx.xxx.xx:1194, sid=1f13cc12 99qqf712d
Mon Nov  5 17:38:34 2018 daemon.notice openvpn(wuseman.uk_client)[3313]: VERIFY OK: depth=1, C=UK, ST=Ceredigion, L=Aberystwyth,  O=wuseman.uk, OU=MyOrganizationalUnit, CN=chapterhouse, name=chapterhouse, emailAddress=xxxxxx@xxxx.com
Mon Nov  5 17:38:34 2018 daemon.notice openvpn(wuseman.uk_client)[3313]: VERIFY OK: nsCertType=SERVER
Mon Nov  5 17:38:34 2018 daemon.notice openvpn(wuseman.uk_client)[3313]: VERIFY OK: depth=0, C=UK, ST=Ceredigion, L=Aberystwyth, O=wuseman.uk, OU=MyOrganizationalUnit, CN=chapterhouse, name=chapterhouse, emailAddress=xxxxxx@xxxx.com
Mon Nov  5 17:38:39 2018 daemon.notice openvpn(wuseman.uk_client)[3313]: Data Channel Encrypt: Cipher 'BF-CBC' initialized with 128 bit key
Mon Nov  5 17:38:39 2018 daemon.notice openvpn(wuseman.uk_client)[3313]: Data Channel Encrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Mon Nov  5 17:38:39 2018 daemon.notice openvpn(wuseman.uk_client)[3313]: Data Channel Decrypt: Cipher 'BF-CBC' initialized with 128 bit key
Mon Nov  5 17:38:39 2018 daemon.notice openvpn(wuseman.uk_client)[3313]: Data Channel Decrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Mon Nov  5 17:38:39 2018 daemon.notice openvpn(wuseman.uk_client)[3313]: Control Channel: TLSv1, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-SHA, 2048 bit RSA
Mon Nov  5 17:38:39 2018 daemon.notice openvpn(wuseman.uk_client)[3313]: [chapterhouse] Peer Connection Initiated with [AF_INET]xxx.xxx.xxx.xx:1194

Video: 
![Screenshot](https://sendit.nu/f/pijYKUxIaECAl.gif)

**Comment by kevdagoat** [comment]
Ahh ok :)

Do you realise that swap is not compiled for the kernel?

**Comment by wuseman** [comment]
Lets continue here: https://github.com/wuseman/TG799VAC-XTREME-17.2-MINT/issues/3
