### ISSUE TITLE
'uci delete' not required before 'uci set'

### ISSUE THREAD

**Issue by flywire** [wuseman/TG799VAC-XTREME-17.2-MINT#4]
https://github.com/wuseman/TG799VAC-XTREME-17.2-MINT#remove-telia-from-all-roles

Not required if set with https://github.com/wuseman/TG799VAC-XTREME-17.2-MINT#and-now-add-our-admin-or-engineer-role-to-these-rules-instead-set-will-override-current-config-so-you-its-not-needed-to-run-above-if-you-want-to-add-admin-to-these-settings-instead

**Comment by wuseman** [comment]
You're right man, i removed this. Thanks @flywire
