### ISSUE TITLE
Decrypt rbi files in Windows

### ISSUE THREAD

**Issue by flywire** [wuseman/TG799VAC-XTREME-17.2-MINT#5]
It is useful to browse through the firmware but often we don't have the hardware it runs on.

I realise the actual hardware will be required to generate the key but an executable that runs under windows would be more convenient than python and linux environments to extract the files.

https://github.com/pedro-n-rocha/secr

Happy to provide more comments and files if feature is of interest.

Edit:
1. Various [OSCK](https://pastelink.net/laft)
2. Various [firmware repository](https://whirlpool.net.au/wiki/hack_technicolor#hw_model_1622) links

**Comment by flywire** [comment]
Note you're already onto it - https://github.com/wuseman/TG799VAC-XTREME-17.2-MINT/issues/2

**Comment by wuseman** [comment]
Correct, but without any results yet still need the firmwar.e

**Comment by flywire** [comment]
I assume you mean the decryption is sucessfull you just need: [Technicolor Firmware Repository](https://whirlpool.net.au/wiki/hw_model_1622).

**Comment by wuseman** [comment]
yes, all these rbi firmwares haven't been accepted by tftp so i guess i need a firmware from telia hence i am trying so hard to find the url+file ;)

**Comment by wuseman** [comment]
I uploaded a zip with all rip files i got from secr tool. If you you get any firmware from these so let me know cause i really need this firmware for vbnt-h version.

https://sendit.nu/f/rip-files.tg799-v3.tar.gz

**Comment by AfoHT** [comment]
I recently upgraded my TG799vac (Telia branded) to 17.2 from the original 15.x over Telias own CWMP. Takes two steps, first 16.2, then 17.2.

Observing the progress via the UART port, I found the following URLs:

```
16.2
http://131.116.22.230:80/1627732r2221004closed.rbi
17.2
http://131.116.22.230:80/172339r1021022closed.rbi
```
This traffic was sent over the mgmt interface, like the rest of the CWMP traffic.

Downloaded the files via
```
$> ssh root@192.168.1.1 -p6666 "wget -O- -q -T 300 http://131.116.22.230:80/1627732r2221004closed.rbi" > 1627732r2221004closed.rbi
$> ssh root@192.168.1.1 -p6666 "wget -O- -q -T 300 http://131.116.22.230:80/172339r1021022closed.rbi" > 172339r1021022closed.rbi
```
Zipped the resulting files, each file about 23MB, both ~46MB (Github only allows 10MB attachments):

https://nextcloud.henriktjader.com/s/z3HxLGapkdnE6TS

During the actual upgrade process running `ps` captured the following:

```
<cut for brevity>
11770 root      1948 S    {upgrade.sh} /bin/sh /usr/lib/cwmpd/transfers/upgrade.sh /tmp/cwmp_downupl_QyxvlK
11829 root      1932 S    {sysupgrade-safe} /bin/sh /usr/bin/sysupgrade-safe -o http://131.116.22.230:80/172339r1021022closed.rbi
11830 root      2016 S    {sysupgrade} /bin/sh /sbin/sysupgrade --safe -o -s http://131.116.22.230:80/172339r1021022closed.rbi
11835 root      2016 S    {sysupgrade} /bin/sh /sbin/sysupgrade --safe -o -s http://131.116.22.230:80/172339r1021022closed.rbi
11855 root      2748 S    signature_checker -b
11856 root      1312 S    mtd -n write - bank_2
11859 root      2016 S    {sysupgrade} /bin/sh /sbin/sysupgrade --safe -o -s http://131.116.22.230:80/172339r1021022closed.rbi
11860 root      2016 S    {sysupgrade} /bin/sh /sbin/sysupgrade --safe -o -s http://131.116.22.230:80/172339r1021022closed.rbi
11861 root      1932 S    tee /tmp/tmp.cCNQTH
11863 root      1932 S    {bli_unseal_aes2} /bin/sh /usr/bin/bli_unseal_aes256
11864 root      1932 S    tee /tmp/tmp.5BeufW
11866 root      1764 S    lua /lib/upgrade/rbi_vrss.lua
11869 root      1936 S    wget -O- -q -T 300 http://131.116.22.230:80/172339r1021022closed.rbi
11876 root      2852 S    bli_unseal_aes256_helper
11877 root      1932 S    {bli_unseal_sha2} /bin/sh /usr/bin/bli_unseal_sha256
11901 root      1932 S    {bli_unseal_sha2} /bin/sh /usr/bin/bli_unseal_sha256
11902 root      1932 S    tee /tmp/tmp.VBnNMt
11903 root      1932 S    {bli_unseal_zip} /bin/sh /usr/bin/bli_unseal_zip
11904 root      1932 S    {bli_unseal_sha2} /bin/sh /usr/bin/bli_unseal_sha256
11905 root      1924 S    sha256sum
11907 root      1928 S    cut -d   -f 1
11913 root      1340 S    bli_unseal_zip_helper
11914 root      1924 S    cat
12163 root      1932 R    ps
```
Trying to recreate the flashing done via CWMP I scp'd a rbi file to /tmp, then tried running
 ```sysupgrade -c -o -s /tmp/17233......closed.rbi -T -v``` which failed with:
```
Image check 'platform_check_image' failed.
```

However, ```sysupgrade-safe -o /tmp/17233......closed.rbi``` proceeded to flash the firmware.

Looking into sysupgrade-safe:

```
<cut>
if [ -z $UPGRADE_URL ]; then                           
        echo "Wrapper around sysupgrade, making it more robust for firmware upgrades."
        echo ""                                                                       
        echo "Usage: $0 {options} <url>"                                              
        echo " Options:"                                                              
        echo "  [-S|--skip-signature] Disables signature checking"                    
        echo "  [-o] Only program inactive bank, do not activate, no reboot"          
        echo "  [--gui] signal an upgrade form the web UI. This will prevent nginx form being killed."
        exit 1                                                                                        
fi
<cut>            
```

This explains why I had to manually activate and reboot even though it had flashed successfully.

As observed above in the `ps` output, the `-o` flag is active.

How I manually swapped between firmwares, based on https://www.crc.id.au/hacking-the-technicolor-tg799vac-and-unlocking-features/comment-page-1/:

```
rm -rf /overlay/`cat /proc/banktable/inactive`
mkdir /overlay/`cat /proc/banktable/inactive`
chmod 755 /overlay/`cat /proc/banktable/inactive`
mkdir /overlay/`cat /proc/banktable/inactive`/etc
chmod 775 /overlay/`cat /proc/banktable/inactive`/etc
echo "echo root:root | chpasswd" > /overlay/`cat /proc/banktable/inactive`/etc/rc.local
echo "sed -i 's/0/1/g' /etc/config/dropbear" >> /overlay/`cat /proc/banktable/inactive`/etc/rc.local
echo "sed -i 's/off/on/g' /etc/config/dropbear" >> /overlay/`cat /proc/banktable/inactive`/etc/rc.local
echo "sed -i 's/#//g' /etc/inittab" >> /overlay/`cat /proc/banktable/inactive`/etc/rc.local
echo "dropbear -p 6666 &" >> /overlay/`cat /proc/banktable/inactive`/etc/rc.local
chmod +x /overlay/`cat /proc/banktable/inactive`/etc/rc.local
echo `cat /proc/banktable/inactive` > /proc/banktable/active
sync
cat /overlay/`cat /proc/banktable/active`/etc/rc.local
```

Unsure why `sysupgrade-safe` worked while `sysupgrade` directly did not.

Hopefully @wuseman will have some fun with these!

**Comment by wuseman** [comment]
Wow, good job man!!! Thank you for uploading these files I really appreciate it. Hopefully I can unbrick my device now =). Downloaded these files now and will try to flash my device via tftp immediately, i keep you updated.

**Comment by LuKePicci** [comment]
@wuseman could you please send me again the results of secr tool running on your device?

**Comment by wuseman** [comment]
@LuKePicci Sorry, i have changed router to the Sagemcom so I cant do this. Hopefully someone else can do this so I leave this thread open.

**Comment by LuKePicci** [comment]
> I uploaded a zip with all rip files i got from secr tool
> https://sendit.nu/f/rip-files.tg799-v3.tar.gz

Did you also delete this archive or you still have it somewhere?

**Comment by LuKePicci** [comment]
> yes, all these rbi firmwares haven't been accepted by tftp so i guess i need a firmware from telia hence i am trying so hard to find the url+file ;)

For the records, it is probably common knowledge nowadays, but this was expected since your board is VANT-R you need to flash a firmware for that board. The board name is also visible in the header of any RBI file. Also, the key to decrypt the RBI payload is unique to that board model.

**Comment by wuseman** [comment]
Oh, no i didn't know this. I still have two technicolor routers that need be flashed.

I backup everything so this file i got somewhere, i will get back to you as soon as I have found it.

**Comment by wuseman** [comment]
YES!! I found them!

https://nr1.nu/rip_files.tar.gz

**Comment by LuKePicci** [comment]
First, I have some problems in downloading such files, it always redirects me to the homepage of nr1.nu...

An RBI has a cleartext header that you can read. In fact I read the header of files shared by @AfoHT and I found the VANT-R mnemonic code. Those firmwares could only be booted on a VANT-R device.

The RBI payload is signed/zipped/encrypted with symmetric key, which is unique for each board. So ig you have the VANT-R key you can decrypt all RBIs for VANT-R.

Please, check the links, then tell me exactly which board those rip_files are relative to.

**Comment by wuseman** [comment]
Sorry, the urls has been fixed.

Okey, I see. I guess VANT-R is TG799 Version 2 then since Version 3 is VANT-H.

These rip_files is from a VBNT-H board 100%.

**Comment by LuKePicci** [comment]
Well, this is very easy to explain, unfortunately the Homeware fork of openwrt has the whole failsafe feature stripped.

**Comment by LuKePicci** [comment]
Ok, from your with the files included in the archive, everybody can decrypt a VBNT-H RBI if they have one.

**Comment by wuseman** [comment]
Okey, how?

**Comment by LuKePicci** [comment]
There are some scripts available to decrypt BLI firmware images. Here is one: https://github.com/pedro-n-rocha/bli223dcryptex

**Comment by wuseman** [comment]
Thanks for info @LuKePicci

**Comment by wuseman** [comment]
Lo, just got a new router today from my ISP finally, this is my fifth i think.

This time i decided to go through entire router BEFORE i did plug in the WAN cable.

The CWMPD key can be found in /etc/cwmpd.db ONLY before you connecting the device to internet for the first time, it wont help to reset router then it's gone forever i guess. 

Peace!

**Comment by flywire** [comment]
All done, any platform with java: https://github.com/Ansuel/Decrypt_RBI_Firmware_Utility

**Comment by wuseman** [comment]
Thanks

**Comment by LuKePicci** [comment]
VBNT-H now listed at https://hack-technicolor.readthedocs.io/en/latest/Firmware%20Repository/#tg799vac-xtream-vbnt-h

**Comment by Iridahonda** [comment]
LuKePicci

VBNT-H now listed at https://hack-technicolor.readthedocs.io/en/latest/Firmware%20Repository/#tg799vac-xtream-vbnt-h

Please can you reseed?

**Comment by wuseman** [comment]
Hey, leeching now, sure I will seed.

**Comment by wuseman** [comment]
I hosting those for you, at the moment only VBNT-H let me know if you
seeding some others. They are available on my nr1.nu domain too:

https://nr1.nu/archive/technicolor/firmware/VBNT-H/1627732h2221002closed.rbi
https://nr1.nu/archive/technicolor/firmware/VBNT-H/172339h1441002closed.rbi
https://nr1.nu/archive/technicolor/firmware/VBNT-H/172339h1441018closed.rbi
https://nr1.nu/archive/technicolor/firmware/VBNT-H/172405h1441028closed.rbi

**Comment by Iridahonda** [comment]
Thanks chaps.  I'm currently on firmware 17.2.0405-1441008-20181017113331 and Autoflashgui doesn't seem to work.  Any ideas?

**Comment by LuKePicci** [comment]
Just follow the instructions: https://hack-technicolor.readthedocs.io/en/stable/

**Comment by wuseman** [comment]
For hack  17.2.0405-1441008-20181017113331 you must downgrade your firmware it wont work with the old method for t his one. See @LuKePicci comments here: https://github.com/wuseman/TG799VAC-XTREME-17.2-MINT/issues/9

**Comment by Iridahonda** [comment]
Cheers.  Much appreciated.
