### ISSUE TITLE
Can't get the short version to work

### ISSUE THREAD

**Issue by mattisas** [wuseman/TG799VAC-XTREME-17.2-MINT#6]
I'll get the following error message "curl: (3) [globbing] bad range in column 2659" when trying the short version.

Firmware Version: 17.2.0339-1021022-20180416103730

**Comment by wuseman** [comment]
There is no curl command used in the short version. You haven't changed anything before you pasting the text into dns field?

**Comment by mattisas** [comment]
Just the IP address
